config/routes.rb
Rails.application.routes.draw do

  mount Credentials::Base => '/'
  mount Users::Base => '/'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :sessions
  # Defines the root path route ("/")
  get "credentials/search" , to: "credentials#search"
  resources :credentials
  #for creating users.
  resources :registrations
  post "login" , to: "sessions#create"
  post "signup" , to: "registrations#create"
  get "editProfile" , to: "registrations#editProfile"
  root "static#origin"
  delete "logout" , to: "sessions#logout"
end

app/models/credential.rb
class Credential < ApplicationRecord
  belongs_to :user
  validates :title, :username, :password, :website, presence: true
end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  before_action :set_credential, only: %i[ show edit update destroy ]
  include CurrentUserConcern
  # GET /credentials or /credentials.json
  def index
    @credentials = @current_user.credentials
  end

  # GET /credentials/1 or /credentials/1.json
  def show
  end

  # GET /credentials/new
  def new
    @credential = Credential.new
  end

  # GET /credentials/1/edit
  def edit
  end

  # POST /credentials or /credentials.json
  def create
    @credential = Credential.new(credential_params)

    respond_to do |format|
      if @credential.save
        format.html { redirect_to credential_url(@credential), notice: "Credential was successfully created." }
        format.json { render :show, status: :created, location: @credential }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credentials/1 or /credentials/1.json
  def update
    respond_to do |format|
      if @credential.update(credential_params)
        format.html { redirect_to credential_url(@credential), notice: "Credential was successfully updated." }
        format.json { render :show, status: :ok, location: @credential }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credentials/1 or /credentials/1.json
  def destroy
    @credential.destroy!

    respond_to do |format|
      format.html { redirect_to credentials_url, notice: "Credential was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def search
    p params[:search]
    searchString = params[:search]
    @credentials = @current_user.credentials
                                 .where('title ILIKE :search OR username ILIKE :search OR website ILIKE :search', search: "%#{searchString}%")
                                 .order(created_at: :desc)
    render :index
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credential
      @credential = Credential.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credential_params
      params.require(:credential).permit(:title, :username, :password, :user_id, :website)
    end
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/views/credentials/_credential.html.erb
<div id="<%= dom_id credential %>">
  <p>
    <strong>Title:</strong>
    <%= credential.title %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= credential.username %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= credential.password %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= credential.website %>
  </p>

</div>

app/views/credentials/_form.html.erb
<%= form_with(model: credential) do |form| %>
  <% if credential.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(credential.errors.count, "error") %> prohibited this credential from being saved:</h2>

      <ul>
        <% credential.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/credentials/edit.html.erb
<h1>Editing credential</h1>

<%
=begin%>
 <%= render "form", credential: @credential %> 
<%
=end%>
<%= form_with model: @credential  do |form| %>
    <%= form.number_field :user_id , value: @current_user.id, type: :hidden%>
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title %>
    <br/><br/>
    <%= form.label :username, "Username:" %>
    <%= form.text_field :username %>
    <br/><br/>
    <%= form.label :password, "Password:" %>
    <%= form.text_field :password %>
    <span class="password-toggle-icon"> <i class="fas fa-eye"></i></span>
    <br/><br/>
    <%= form.label :website, "Website:" %>
    <%= form.text_field :website %>
    <br/><br/>
    <%= form.button  %>
<%end%>

<br>

<div>
  <%= link_to "Show this credential", @credential %> |
  <%= link_to "Back to credentials", credentials_path %>
</div>

app/views/credentials/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Credentials</h1>

<div id="credentials">
  <% @credentials.each do |credential| %>
    <%= render credential %>
    <p>
      <%= link_to "Show this credential", credential %>
    </p>
  <% end %>
</div>
<br/>
<%= link_to "Add New credential", new_credential_path %>

app/views/credentials/new.html.erb
<h1>New credential</h1>

<%
=begin%>
 <%= render "form", credential: @credential %> 
<%
=end%>


<%= form_with model: @credential  do |form| %>
    <%= form.number_field :user_id , value: @current_user.id, type: :hidden%>
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title %>
    <br/><br/>
    <%= form.label :username, "Username:" %>
    <%= form.text_field :username %>
    <span class="password-toggle-icon"><i class="fas fa-eye"></i></span>
    <br/><br/>
    <%= form.label :password, "Password:" %>
    <%= form.text_field :password %>
    <br/><br/>
    <%= form.label :website, "Website:" %>
    <%= form.text_field :website %>
    <br/><br/>
    <%= form.button  %>
<%end%>
<br>

<div>
  <%= link_to "Back to credentials", credentials_path %>
</div>

app/views/credentials/search.html.erb
<p style="color: green"><%= notice %></p>

<h1>Credentials</h1>

<div id="credentials">
  <% @credentials.each do |credential| %>
    <%= render credential %>
    <p>
      <%= link_to "Show this credential", credential %>
    </p>
  <% end %>
</div>
<br/>
<%= link_to "Add New credential", new_credential_path %>

app/views/credentials/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @credential %>

<div>
  <%= link_to "Edit this credential", edit_credential_path(@credential) %> |
  <%= link_to "Back to Home ", credentials_path %>
  <br/><br/>
  <%= button_to "Remove credential", @credential, method: :delete %>
</div>