config/routes.rb
Rails.application.routes.draw do

  mount Credentials::Base => '/'
  mount Users::Base => '/'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :sessions
  # Defines the root path route ("/")
  get "credentials/search" , to: "credentials#search"
  resources :credentials
  #for creating users.
  resources :registrations
  post "login" , to: "sessions#create"
  post "signup" , to: "registrations#create"
  get "editProfile" , to: "registrations#editProfile"
  root "static#origin"
  delete "logout" , to: "sessions#logout"
end

app/views/common/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%if @current_user%>
        <li class="nav-item">
            <%= link_to "Credentials", credentials_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
            <%= link_to "Edit Profile", edit_registration_path(@current_user), class: "nav-link active" %> 
        <li class="nav-item">
            <%= button_to "Sign out", logout_path, method: :delete ,data: { turbolinks: false } ,class: "nav-link"%>
        </li>
        <!-- need to add action/url, method!-->
      <form class="d-flex" role="search" action="/credentials/search" method= "get">
        <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>        
      <%else%>
        <li class="nav-item">
            <%= link_to "Home", new_session_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Log in", new_session_path , class: "nav-link"%>
        </li>
         <li class="nav-item">
            <%= link_to "Sign up", new_registration_path, class: "nav-link"%>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>